// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"pfn-backend/internal/provider"
)

// Injectors from wire.go:

func InitializeApplication(configPath string) (*provider.Server, error) {
	config, err := provider.ProvideConfig(configPath)
	if err != nil {
		return nil, err
	}
	logger, err := provider.ProviderLogger(config)
	if err != nil {
		return nil, err
	}
	database, err := provider.ProviderDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	userRepository := provider.ProvideUserRepository(database)
	refreshTokenRepository := provider.ProvideRefreshTokenRepository(database)
	jwtManager := provider.ProvideJWTManager(config)
	service := provider.ProvideAuthService(userRepository, refreshTokenRepository, jwtManager, logger)
	authHandler := provider.ProvideAuthHandler(service, logger)
	userService := provider.ProvideUserService(userRepository)
	userHandler := provider.ProvideUserHandler(userService)
	cardRepository := provider.ProvideCardRepository(database)
	cardService := provider.ProvideCardService(cardRepository)
	cardHandler := provider.ProvideCardHandler(cardService)
	transactionRepository := provider.ProvideTransactionRepository(database)
	transactionService := provider.ProvideTransactionService(transactionRepository, cardRepository)
	transactionHandler := provider.ProvideTransactionHandler(transactionService)
	categoryRepository := provider.ProvideCategoryRepository(database)
	categoryService := provider.ProvideCategoryService(categoryRepository)
	categoryHandler := provider.ProvideCategoryHandler(categoryService)
	authMiddleware := provider.ProvideAuthMiddleware(jwtManager, logger)
	loggerMiddleware := provider.ProvideLoggerMiddleware(logger)
	corsMiddleware := provider.ProvideCORSMiddleware(config)
	recoveryMiddleware := provider.ProvideRecoveryMiddleware(logger)
	router := provider.ProvideRouter(config, authHandler, userHandler, cardHandler, transactionHandler, categoryHandler, authMiddleware, loggerMiddleware, corsMiddleware, recoveryMiddleware)
	server := provider.ProvideServer(config, router, database, logger)
	return server, nil
}
