// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"pfn-backend/internal/app/postgres"
	"pfn-backend/internal/config"
	"pfn-backend/internal/pkg/logger"
	"pfn-backend/internal/provider"
)

// Injectors from wire.go:

func InitializeApplication(configPath string) (*Application, error) {
	config, err := provider.ProvideConfig(configPath)
	if err != nil {
		return nil, err
	}
	logger, err := provider.ProviderLogger(config)
	if err != nil {
		return nil, err
	}
	database, err := provider.ProviderDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	application := &Application{
		Logger: logger,
		DB:     database,
		Config: config,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Logger *logger.Logger
	DB     *postgres.Database
	Config *config.Config
}
